# Data Loading

This notebook contains the steps for the loading the dataset and gathering info on the dataset.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

raw_df = pd.read_csv(r"dft-road-casualty-statistics-collision-2025.csv")
raw_df.head()

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,202517M101925,2025,17M101925,447673.0,519279.0,-1.26420,54.56650,17,3,1,...,-1,0,1,1,2,E01012014,3,1,0.0,1.0
1,202517L205225,2025,17L205225,454611.0,518597.0,-1.15704,54.55967,17,3,2,...,-1,0,1,1,2,E01012173,3,1,0.0,1.0
2,2025070971700,2025,070971700,354476.0,382656.0,-2.68516,53.33884,7,3,2,...,-1,0,2,1,2,E01012444,3,1,0.0,1.0
3,2025070403274,2025,070403274,361793.0,393163.0,-2.57655,53.43386,7,3,2,...,-1,0,2,3,2,E01012468,3,1,0.0,1.0
4,2025071000604,2025,071000604,366083.0,389327.0,-2.51157,53.39967,7,3,7,...,-1,0,2,1,1,E01012551,3,1,0.0,1.0

In [2]:
raw_df.shape

(101525, 44)

In [3]:
# Making a copy of the raw data

cleaned_df = raw_df.copy()

In [4]:
cleaned_df.shape

(101525, 44)

In [5]:
cleaned_df.head()

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,202517M101925,2025,17M101925,447673.0,519279.0,-1.26420,54.56650,17,3,1,...,-1,0,1,1,2,E01012014,3,1,0.0,1.0
1,202517L205225,2025,17L205225,454611.0,518597.0,-1.15704,54.55967,17,3,2,...,-1,0,1,1,2,E01012173,3,1,0.0,1.0
2,2025070971700,2025,070971700,354476.0,382656.0,-2.68516,53.33884,7,3,2,...,-1,0,2,1,2,E01012444,3,1,0.0,1.0
3,2025070403274,2025,070403274,361793.0,393163.0,-2.57655,53.43386,7,3,2,...,-1,0,2,3,2,E01012468,3,1,0.0,1.0
4,2025071000604,2025,071000604,366083.0,389327.0,-2.51157,53.39967,7,3,7,...,-1,0,2,1,1,E01012551,3,1,0.0,1.0

In [6]:
cleaned_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101525 entries, 0 to 101524
Data columns (total 44 columns):
 #   Column                                            Non-Null Count   Dtype
---  ------                                            --------------   -----
 0   collision_index                                   101525 non-null  str
 1   collision_year                                    101525 non-null  int64
 2   collision_ref_no                                  101525 non-null  str
 3   location_easting_osgr                             101523 non-null  float64
 4   location_northing_osgr                            101523 non-null  float64
 5   longitude                                         101523 non-null  float64
 6   latitude                                          101523 non-null  float64
 7   police_force                                      101525 non-null  int64
 8   collision_severity                                101525 non-null  int64
 9   number_of_vehicles                                101525 non-null  int64
 10  number_of_casualties                              101525 non-null  int64
 11  date                                              101525 non-null  str
 12  day_of_week                                       101525 non-null  int64
 13  time                                              101525 non-null  str
 14  local_authority_district                          101525 non-null  int64
 15  local_authority_ons_district                      101525 non-null  str
 16  local_authority_highway                           101525 non-null  str
 17  local_authority_highway_current                   101525 non-null  str
 18  first_road_class                                  101525 non-null  int64
 19  first_road_number                                 101525 non-null  int64
 20  road_type                                         101525 non-null  int64
 21  speed_limit                                       101525 non-null  int64
 22  junction_detail_historic                          101525 non-null  int64
 23  junction_detail                                   101525 non-null  int64
 24  junction_control                                  101525 non-null  int64
 25  second_road_class                                 101525 non-null  int64
 26  second_road_number                                101525 non-null  int64
 27  pedestrian_crossing_human_control_historic        101525 non-null  int64
 28  pedestrian_crossing_physical_facilities_historic  101525 non-null  int64
 29  pedestrian_crossing                               101525 non-null  int64
 30  light_conditions                                  101525 non-null  int64
 31  weather_conditions                                101525 non-null  int64
 32  road_surface_conditions                           101525 non-null  int64
 33  special_conditions_at_site                        101525 non-null  int64
 34  carriageway_hazards_historic                      101525 non-null  int64
 35  carriageway_hazards                               101525 non-null  int64
 36  urban_or_rural_area                               101525 non-null  int64
 37  did_police_officer_attend_scene_of_accident       101525 non-null  int64
 38  trunk_road_flag                                   101525 non-null  int64
 39  lsoa_of_accident_location                         101525 non-null  str
 40  enhanced_severity_collision                       101525 non-null  int64
 41  collision_injury_based                            101525 non-null  int64
 42  collision_adjusted_severity_serious               101525 non-null  float64
 43  collision_adjusted_severity_slight                101525 non-null  float64
dtypes: float64(6), int64(30), str(8)
memory usage: 41.1 MB

In [7]:
cleaned_df.describe()

,collision_year,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,day_of_week,...,special_conditions_at_site,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
count,101525.0,101523.000000,1.015230e+05,101523.000000,101523.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,...,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000
mean,2025.0,454027.068812,2.764592e+05,-1.223959,52.375658,27.962522,2.723250,1.811849,1.259621,4.126097,...,-0.834652,-0.839399,1.265324,1.338646,1.523585,1.726461,3.191470,0.865284,0.253561,0.732127
std,0.0,92739.506456,1.452150e+05,1.356983,1.308239,24.075091,0.478315,0.689631,0.816679,1.926299,...,0.631565,0.598058,8.722224,0.473335,0.838330,0.786635,2.209339,0.341421,0.428807,0.436721
min,2025.0,71253.000000,1.023700e+04,-7.417720,49.912530,1.000000,1.000000,1.000000,1.000000,1.000000,...,-1.000000,-1.000000,-1.000000,1.000000,1.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000
25%,2025.0,392107.500000,1.753650e+05,-2.118700,51.464460,5.000000,2.000000,1.000000,1.000000,2.000000,...,-1.000000,-1.000000,0.000000,1.000000,1.000000,2.000000,3.000000,1.000000,0.000000,0.000000
50%,2025.0,458353.000000,2.228290e+05,-1.138910,51.888640,23.000000,3.000000,2.000000,1.000000,4.000000,...,-1.000000,-1.000000,0.000000,1.000000,1.000000,2.000000,3.000000,1.000000,0.000000,1.000000
75%,2025.0,529150.500000,3.813935e+05,-0.137910,53.325860,45.000000,3.000000,2.000000,1.000000,6.000000,...,-1.000000,-1.000000,0.000000,2.000000,2.000000,2.000000,3.000000,1.000000,0.229840,1.000000
max,2025.0,655126.000000,1.162591e+06,1.755590,60.345250,99.000000,3.000000,17.000000,142.000000,7.000000,...,9.000000,9.000000,99.000000,3.000000,3.000000,2.000000,7.000000,1.000000,1.000000,1.000000

In [8]:
cleaned_df.describe(include=["object"])

C:\Users\Asus\AppData\Local\Temp\ipykernel_6140\1211194903.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cleaned_df.describe(include=["object"])

,collision_index,collision_ref_no,date,time,local_authority_ons_district,local_authority_highway,local_authority_highway_current,lsoa_of_accident_location
count,101525,101525,101525,101525,101525,101525,101525,101525
unique,101525,101525,365,1440,351,208,208,27179
top,202517M101925,17M101925,19/12/2025,17:00,E08000025,E10000016,E10000016,-1
freq,1,1,412,891,2307,2957,2957,4107

In [9]:
cleaned_df.columns

Index(['collision_index', 'collision_year', 'collision_ref_no',
       'location_easting_osgr', 'location_northing_osgr', 'longitude',
       'latitude', 'police_force', 'collision_severity', 'number_of_vehicles',
       'number_of_casualties', 'date', 'day_of_week', 'time',
       'local_authority_district', 'local_authority_ons_district',
       'local_authority_highway', 'local_authority_highway_current',
       'first_road_class', 'first_road_number', 'road_type', 'speed_limit',
       'junction_detail_historic', 'junction_detail', 'junction_control',
       'second_road_class', 'second_road_number',
       'pedestrian_crossing_human_control_historic',
       'pedestrian_crossing_physical_facilities_historic',
       'pedestrian_crossing', 'light_conditions', 'weather_conditions',
       'road_surface_conditions', 'special_conditions_at_site',
       'carriageway_hazards_historic', 'carriageway_hazards',
       'urban_or_rural_area', 'did_police_officer_attend_scene_of_accident',
       'trunk_road_flag', 'lsoa_of_accident_location',
       'enhanced_severity_collision', 'collision_injury_based',
       'collision_adjusted_severity_serious',
       'collision_adjusted_severity_slight'],
      dtype='str')

In [10]:
cleaned_df.dtypes

collision_index                                         str
collision_year                                        int64
collision_ref_no                                        str
location_easting_osgr                               float64
location_northing_osgr                              float64
longitude                                           float64
latitude                                            float64
police_force                                          int64
collision_severity                                    int64
number_of_vehicles                                    int64
number_of_casualties                                  int64
date                                                    str
day_of_week                                           int64
time                                                    str
local_authority_district                              int64
local_authority_ons_district                            str
local_authority_highway                                 str
local_authority_highway_current                         str
first_road_class                                      int64
first_road_number                                     int64
road_type                                             int64
speed_limit                                           int64
junction_detail_historic                              int64
junction_detail                                       int64
junction_control                                      int64
second_road_class                                     int64
second_road_number                                    int64
pedestrian_crossing_human_control_historic            int64
pedestrian_crossing_physical_facilities_historic      int64
pedestrian_crossing                                   int64
light_conditions                                      int64
weather_conditions                                    int64
road_surface_conditions                               int64
special_conditions_at_site                            int64
carriageway_hazards_historic                          int64
carriageway_hazards                                   int64
urban_or_rural_area                                   int64
did_police_officer_attend_scene_of_accident           int64
trunk_road_flag                                       int64
lsoa_of_accident_location                               str
enhanced_severity_collision                           int64
collision_injury_based                                int64
collision_adjusted_severity_serious                 float64
collision_adjusted_severity_slight                  float64
dtype: object